version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/real_time_bidding
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_time_bidding
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
